#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-Factory
version:      1.03
version_from: lib/Class/Factory.pm
installdirs:  site
requires:
    Test::More:                    0.4

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
